const getPassiveIcon = (icon) => {
    switch (icon) {
        case 0: return 'Weak';
        case 1: return 'DEF-Related Stats Weakening';
        case 2: return 'Power Burst Boost';
        case 3: return 'Stats Boost';
        case 4: return 'Bonus-Attack';
        case 5: return 'Immunity';
        case 6: return 'ATK-Related Stats Boost';
        case 7: return 'Lone Wolf';
        case 8: return 'Boost';
        case 9: return 'Group ATK Boost';
        case 10: return 'CRIT DMG Boost';
        case 11: return 'Power Burst Boost';
        case 12: return 'DMG Boost';
        case 13: return 'HP Restoration';
        case 14: return 'Penetration Boost';
        case 15: return 'Random Debuff';
        case 16: return 'ATK/DEF Boost';
        case 17: return 'Shield';
        case 18: return 'Group Boost';
        case 19: return 'Unyielding';
        case 20: return 'Group Shield';
        case 21: return 'Retaliation';
        case 22: return 'Attacking Blood Rage Applying';
        case 23: return 'Additional DMG';
        case 24: return 'Attacked Blood Rage Applying';
        case 25: return 'Basic Stats Boost';
        case 26: return 'Skill Level Up';
        case 27: return 'Weak Immunity';
        case 28: return 'Energy Intaking';
        case 29: return 'Energy Boost';
        case 30: return 'Charge-Up';
        case 31: return 'Block Chance Reduction';
        case 32: return 'Charge-Up Burst';
        case 33: return 'Lifesteal Boost';
        case 34: return 'Attack Boost';
        case 35: return 'Additional Damage';
        case 36: return 'Restoration Boost';
        case 37: return 'Group ATK Boost';
        case 38: return 'Block Ignoring';
        case 39: return 'HP Boost';
        case 40: return 'Weaken';
        case 41: return 'CRIT Resistance Weakening';
        case 42: return 'Dispel';
        case 43: return 'Lock HP Lost';
        case 44: return 'DMG Resist';
        case 45: return 'Group Defense Weakening';
        case 46: return 'Scorched';
        case 47: return 'Debuff Spreading';
        case 48: return 'Thunder';
        case 49: return 'Incapacitation Boost';
        case 50: return 'Numb Reaction';
        case 51: return 'Incapacitation Strike';
        case 52: return 'Random Attack';
        case 53: return 'Adversity';
        case 54: return 'Survival Boost';
        case 55: return 'Group CRIT Weakening';
        case 56: return 'Debuff Removal';
        case 57: return 'Provoke';
        case 58: return 'Strategic Deployment';
        case 59: return 'Max HP Boost';
        case 60: return 'DMG Decrease';
        case 61: return 'Group Restoration';
        case 62: return 'Group Boost';
        case 63: return 'DMG Amplification';
        case 64: return 'Gain Extra Energy';
        case 65: return 'Block Boost';
        case 66: return 'Basic & Restoration Boost';
        case 67: return 'DMG Decrease';
        case 68: return 'Inspire';
        case 69: return 'Encourage';
        case 70: return 'Rage';
        case 71: return 'ATK & DEF Weakening';
        case 72: return 'Surprise Attack';
        case 73: return 'Weak Reduction';
        case 74: return 'Sanity Collapse';
        default: return 'Unknown';
    }
};

export default getPassiveIcon;